src/Entity/Period.php
<?php

namespace App\Entity;

use App\Repository\PeriodRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

/**
 * @author Caron Baptiste
 */
#[ORM\Entity(repositoryClass: PeriodRepository::class)]
class Period
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $Period_Start = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $Period_End = null;

    #[ORM\Column(length: 255)]
    private ?string $Session = null;

    #[ORM\OneToMany(mappedBy: 'Period', targetEntity: Lesson::class)]
    private Collection $lessons;

    #[ORM\Column]
    private ?bool $currentPeriod = false;

    public function __construct()
    {
        $this->lessons = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPeriodStart(): ?\DateTimeInterface
    {
        return $this->Period_Start;
    }

    public function setPeriodStart(\DateTimeInterface $Period_Start): self
    {
        $this->Period_Start = $Period_Start;

        return $this;
    }

    public function getPeriodEnd(): ?\DateTimeInterface
    {
        return $this->Period_End;
    }

    public function setPeriodEnd(\DateTimeInterface $Period_End): self
    {
        $this->Period_End = $Period_End;

        return $this;
    }

    public function getSession(): ?string
    {
        return $this->Session;
    }

    public function setSession(string $Session): self
    {
        $this->Session = $Session;

        return $this;
    }

    /**
     * @return Collection<int, Lesson>
     */
    public function getLessons(): Collection
    {
        return $this->lessons;
    }

    public function addLesson(Lesson $lesson): self
    {
        if (!$this->lessons->contains($lesson)) {
            $this->lessons->add($lesson);
            $lesson->setPeriod($this);
        }

        return $this;
    }

    public function removeLesson(Lesson $lesson): self
    {
        if ($this->lessons->removeElement($lesson)) {
            // set the owning side to null (unless already changed)
            if ($lesson->getPeriod() === $this) {
                $lesson->setPeriod(null);
            }
        }

        return $this;
    }

    public function isCurrentPeriod(): ?bool
    {
        return $this->currentPeriod;
    }

    public function setCurrentPeriod(bool $currentPeriod): self
    {
        $this->currentPeriod = $currentPeriod;

        return $this;
    }
}

src/Form/PeriodType.php
<?php

namespace App\Form;

use App\Entity\Period;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PeriodType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('Period_Start', DateType::class, [
                'attr' => [
                    'class' => 'form-control some-start',
                    'id' => 'start'
                ],
                'widget' => 'single_text',
                'html5' => false,
                'label' => 'Date de début',
                'input_format' => 'd/m/Y',
                'format' => 'd/m/Y',
                'label_attr' => [
                    'class' => 'form-label'
                ]
            ])
            ->add('Period_End', DateType::class, [
                'attr' => [
                    'class' => 'form-control some-end',
                    'id' => 'end'
                ],
                'widget' => 'single_text',
                'html5' => false,
                'input_format' => 'd/m/Y',
                'format' => 'd/m/Y',
                'label' => 'Date de fin',
                'label_attr' => [
                    'class' => 'form-label'
                ]
            ])
            ->add('Session', TextType::class, [
                'attr' => [
                    'class' => 'form-control'
                ],
                'label' => 'Nom de la periode',
                'label_attr' => [
                    'class' => 'form-label'
                ]
            ])
            ->add('currentPeriod', CheckboxType::class, [
                'attr' => [
                    'class' => 'form-check-input mt-5'
                ]
                ,
                'compound' => true,
                'required' => false,
                'label' => 'Periode en cours ?',
                'label_attr' => [
                    'class' => 'form-label me-5 mt-5'
                ]
            ])
            ->add('submit', SubmitType::class, [
                'attr' => [
                    'class' => 'btn btn-outline-primary mt-4',
                ],
                'label' => 'Valider',
                ]);

    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Period::class,
        ]);
    }
}

src/Controller/PeriodController.php
<?php

namespace App\Controller;


use App\Entity\Period;
use App\Form\PeriodType;
use App\Repository\PeriodRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class PeriodController extends AbstractController
{

    #[Route('/period', name: 'app_period' , methods: [ 'GET','POST'])]
    public function index(Request $request, PeriodRepository $repository): Response
    {
        $period = $repository->findAll();

        return $this->render('period/index.html.twig', [
            'periods' => $period,
        ]);
    }

    #[Route('/period/new', name: 'app_period_new' , methods: [ 'GET','POST'])]
    public function new(Request $request, PeriodRepository $repository, EntityManagerInterface $manager): Response
    {
        $period = new Period();
        $form = $this->createForm(PeriodType::class, $period);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $period = $form->getData();
            $manager->persist($period);
            $manager->flush();

            return $this->redirectToRoute('app_period');
        }
        return $this->render('period/form.html.twig', [
            'form' => $form,
            'route' => 'app_period_new'
        ]);
    }

    #[Route('/period/{id}', name: 'app_period_edit' , methods: [ 'GET','POST'])]
    public function edit(Request $request, Period $period): Response
    {
        $form = $this->createForm(PeriodType::class, $period);
        return $this->render('period/form.html.twig', [
            'form' => $form,
            'route' => 'app_period_edit'
        ]);
    }
}

templates/period/form.html.twig
{% extends 'base.html.twig' %}

{% block title %}Class Checker -
    {% if route is same as 'app_period_new' %}
    Creation d'une période
    {% elseif route is same as 'app_period_edit' %}
    Modification d'une période
    {% endif %}
{% endblock %}
{% block style %}
    <link href="
https://cdn.jsdelivr.net/npm/lightpick@1.6.2/css/lightpick.min.css
" rel="stylesheet">
    <link href="
{{ asset('assets/css/mdtimepicker.min.css') }}
" rel="stylesheet">
    <link href="
{{ asset('assets/css/mdtimepicker-theme.css') }}
" rel="stylesheet">

{% endblock %}
{% block body %}
    <div class="container mb-4">

        <h1 class="mt-2 d-flex justify-content-center text-dark">
            {% if route is same as 'app_period_new' %}
                Creation d'une période
            {% elseif route is same as 'app_period_edit' %}
                Modification d'une période
            {% endif %}
        </h1>

        {{ form_start(form) }}


        <div class="row mt-3">
            <div class="col">
                {{ form_row(form.Period_Start) }}
                <div class="my-custom-class-for-errors">
                    {{ form_errors(form.Period_Start) }}
                </div>
            </div>

            <div class="col" id="some-custom-id">
                {{ form_row(form.Period_End) }}
                <div class="my-custom-class-for-errors">
                    {{ form_errors(form.Period_End) }}
                </div>
            </div>
        </div>

        <div class="row mt-3">
            <div class="col">
                {{ form_row(form.Session) }}
                <div class="my-custom-class-for-errors">
                    {{ form_errors(form.Session) }}
                </div>
            </div>
            <div class="col">
                {{ form_row(form.currentPeriod) }}
                <div class="my-custom-class-for-errors">
                    {{ form_errors(form.currentPeriod) }}
                </div>
            </div>
        </div>
        <div>
            <div class="mt-3 d-flex justify-content-evenly">
                <a class="mt-4 ms-5 btn btn-outline-danger" href="{{ path('app_period') }}">Annuler</a>
                {{ form_row(form.submit) }}
            </div>
        </div>

        {{ form_end(form) }}
    </div>



{% endblock %}
{% block script %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.22.2/moment.min.js"></script>
    <script src="
{{ asset('assets/js/mdtimepicker.min.js') }}
"></script>
    <script src="
https://cdn.jsdelivr.net/npm/lightpick@1.6.2/lightpick.min.js
"></script>
    <script src="{{ asset('assets/js/datePickerPeriod.js') }}"></script>
{% endblock %}

templates/period/index.html.twig
{% extends 'base.html.twig' %}

{% block style %}
    <link href="
{{ asset('assets/vendor/datatables/dataTables.bootstrap4.min.css') }}
" rel="stylesheet">
    <link href="
{{ asset('assets/css/lessonStyle.css') }}
" rel="stylesheet">
    <link href="https://cdn.datatables.net/buttons/2.3.6/css/buttons.dataTables.min.css" rel="stylesheet">

{% endblock %}
{% block title %}Class Checker - Index période{% endblock %}

{% block body %}
    {% for message in app.flashes("error") %}
        <div class="flash" data-state="error">
            <strong>{{message}}</strong></div>

    {% endfor %}
<div id="alert">

</div>
        <div class="me-5 ms-5 pt-2 mb-4" style="width: 100%">
            <h1 class="justify-content-center d-flex text-center text-dark"> Liste des période</h1>
            <a class="btn btn-outline-primary" href="{{ path('app_period_new') }}">Ajouter</a>
            <table class="table table-hover table-bordered w-100" id="dataTable">
                <thead >
                <tr class="table-primary">
                    <th>Date</th>
                    <th>Nom</th>
                    <th>Status</th>
                    <th>ACTION</th>
                </tr>
                </thead>


                    <tbody id="period">
                    {% for period in periods %}
                    <tr class="" id="{{ period.id }}">
                        <td class="ps-2 toolTip" style="max-width: 10em; max-height: 5em;" >
                            du {{ period.PeriodStart | date('d/m/Y') }} au {{ period.PeriodEnd | date('d/m/Y') }}
                        </td>
                        <td class="ps-2">{{ period.session }}</td>
                        <td>
                            {% if period.currentPeriod is same as false %} Non
                            {% elseif period.currentPeriod is same as true %} Actuelle
                            {% endif %}
                        </td>

                        <td class="ps-2" style="width:10em ">
                            <a class="btn btn-outline-warning btn-sm" href="{{ path('app_period_edit',{'id':period.id}) }}"> <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
                                    <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
                                    <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"/>
                                </svg></a>
                        </td>

                    </tr>
                    {% endfor %}
                    </tbody>

            </table>
        </div>

{% endblock %}

{% block script %}
    <script src="{{ asset('assets/js/ajaxDeleteLesson.js')}}">  </script>
{% endblock %}