src/Entity/Absence.php
<?php

namespace App\Entity;

use App\Repository\AbsenceRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

#[ORM\Entity(repositoryClass: AbsenceRepository::class)]
#[ORM\UniqueConstraint( name: 'clee' , fields: ['students', 'session'])]
class Absence
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $Date_justify = null;

    #[ORM\ManyToOne(inversedBy: 'absences')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Student $students = null;

    #[ORM\ManyToOne(inversedBy: 'absences')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Justify $justify = null;

    #[ORM\ManyToOne(inversedBy: 'absences')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Session $session = null;




    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateJustify(): ?\DateTimeInterface
    {
        return $this->Date_justify;
    }

    public function setDateJustify(\DateTimeInterface $Date_justify): self
    {
        $this->Date_justify = $Date_justify;

        return $this;
    }


    public function getStudents(): ?Student
    {
        return $this->students;
    }

    public function setStudents(?Student $students): self
    {
        $this->students = $students;

        return $this;
    }

    public function getJustify(): ?Justify
    {
        return $this->justify;
    }

    public function setJustify(?Justify $justify): self
    {
        $this->justify = $justify;

        return $this;
    }

    public function getSession(): ?Session
    {
        return $this->session;
    }

    public function setSession(?Session $session): self
    {
        $this->session = $session;

        return $this;
    }

}

src/Entity/Lesson.php
<?php

namespace App\Entity;

use App\Repository\LessonRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;


/**
 * @author Baptiste Caron
 *
 */
#[ORM\Entity(repositoryClass: LessonRepository::class)]

class Lesson
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    /**
     * @var string|null
     *
     */
    #[ORM\Column(length: 255)]
    private ?string $Label = null;

    /**
     * @var int|null
     */
    #[ORM\Column]
    private ?int $Number_Max_Of_Students = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $Time_Start = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $Time_End = null;

    #[ORM\Column(type: Types::TIME_MUTABLE)]
    private ?\DateTimeInterface $Hours_Start = null;

    #[ORM\Column(type: Types::TIME_MUTABLE)]
    private ?\DateTimeInterface $Hours_End = null;

    #[ORM\Column(length: 255)]
    private ?string $Day = null;

    #[ORM\ManyToOne(inversedBy: 'lessons')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $teacher = null;



    #[ORM\OneToMany(mappedBy: 'Lessons', targetEntity: ToHave::class, orphanRemoval: false)]
    private Collection $toHave;

    #[ORM\ManyToOne(inversedBy: 'lessons')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Period $Period = null;

    #[ORM\OneToMany(mappedBy: 'lesson', targetEntity: Session::class, orphanRemoval: false)]
    private Collection $sessions;



    public function __construct()
    {
        $this->toHave = new ArrayCollection();
        $this->sessions = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLabel(): ?string
    {
        return $this->Label;
    }

    public function setLabel(string $Label): self
    {
        $this->Label = $Label;

        return $this;
    }

    public function getNumberMaxOfStudents(): ?int
    {
        return $this->Number_Max_Of_Students;
    }

    public function setNumberMaxOfStudents(int $Number_Max_Of_Students): self
    {
        $this->Number_Max_Of_Students = $Number_Max_Of_Students;

        return $this;
    }

    public function getTimeStart(): ?\DateTimeInterface
    {
        return $this->Time_Start;
    }

    public function setTimeStart(\DateTimeInterface $Time_Start): self
    {
        $this->Time_Start = $Time_Start;

        return $this;
    }

    public function getTimeEnd(): ?\DateTimeInterface
    {
        return $this->Time_End;
    }

    public function setTimeEnd(\DateTimeInterface $Time_End): self
    {
        $this->Time_End = $Time_End;

        return $this;
    }

    public function getHoursStart(): ?\DateTimeInterface
    {
        return $this->Hours_Start;
    }

    public function setHoursStart(\DateTimeInterface $Hours_Start): self
    {
        $this->Hours_Start = $Hours_Start;

        return $this;
    }

    public function getHoursEnd(): ?\DateTimeInterface
    {
        return $this->Hours_End;
    }

    public function setHoursEnd(\DateTimeInterface $Hours_End): self
    {
        $this->Hours_End = $Hours_End;

        return $this;
    }

    public function getDay(): ?string
    {
        return $this->Day;
    }

    public function setDay(string $Day): self
    {
        $this->Day = $Day;

        return $this;
    }

    public function getTeacher(): ?User
    {
        return $this->teacher;
    }

    public function setTeacher(?User $teacher): self
    {
        $this->teacher = $teacher;

        return $this;
    }

    public function __toString(){
        return $this->Label ?? '';
    }

    /**
     * @return Collection<int, ToHave>
     */
    public function getToHave(): Collection
    {
        return $this->toHave;
    }

    public function addToHave(ToHave $toHave): self
    {
        if (!$this->toHave->contains($toHave)) {
            $this->toHave->add($toHave);
            $toHave->setLessons($this);
        }

        return $this;
    }

    public function removeToHave(ToHave $toHave): self
    {
        if ($this->toHave->removeElement($toHave)) {
            if ($toHave->getLessons() === $this) {
                $toHave->setLessons(null);
            }
        }

        return $this;
    }

    public function getPeriod(): ?Period
    {
        return $this->Period;
    }

    public function setPeriod(?Period $Period): self
    {
        $this->Period = $Period;

        return $this;
    }

    /**
     * @return Collection<int, Session>
     */
    public function getSessions(): Collection
    {
        return $this->sessions;
    }

    public function addSession(Session $session): self
    {
        if (!$this->sessions->contains($session)) {
            $this->sessions->add($session);
            $session->setLesson($this);
        }

        return $this;
    }

    public function removeSession(Session $session): self
    {
        if ($this->sessions->removeElement($session)) {
            // set the owning side to null (unless already changed)
            if ($session->getLesson() === $this) {
                $session->setLesson(null);
            }
        }

        return $this;
    }

}

src/Entity/Session.php
<?php

namespace App\Entity;

use App\Repository\SessionRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: SessionRepository::class)]
class Session
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date = null;

    #[ORM\Column(type: Types::TIME_MUTABLE)]
    private ?\DateTimeInterface $hourStart = null;

    #[ORM\Column(type: Types::TIME_MUTABLE)]
    private ?\DateTimeInterface $hourEnd = null;

    #[ORM\Column(length: 255)]
    private ?string $label = null;

    #[ORM\Column(length: 255)]
    private ?string $day = null;

    #[ORM\ManyToOne(inversedBy: 'sessions')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Lesson $lesson = null;

    #[ORM\OneToMany(mappedBy: 'session', targetEntity: Absence::class)]
    private Collection $absences;

    public function __construct()
    {
        $this->absences = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getHourStart(): ?\DateTimeInterface
    {
        return $this->hourStart;
    }

    public function setHourStart(\DateTimeInterface $hourStart): self
    {
        $this->hourStart = $hourStart;

        return $this;
    }

    public function getHourEnd(): ?\DateTimeInterface
    {
        return $this->hourEnd;
    }

    public function setHourEnd(\DateTimeInterface $hourEnd): self
    {
        $this->hourEnd = $hourEnd;

        return $this;
    }

    public function getLabel(): ?string
    {
        return $this->label;
    }

    public function setLabel(string $label): self
    {
        $this->label = $label;

        return $this;
    }

    public function getDay(): ?string
    {
        return $this->day;
    }

    public function setDay(string $day): self
    {
        $this->day = $day;

        return $this;
    }

    public function getLesson(): ?Lesson
    {
        return $this->lesson;
    }

    public function setLesson(?Lesson $lesson): self
    {
        $this->lesson = $lesson;

        return $this;
    }

    /**
     * @return Collection<int, Absence>
     */
    public function getAbsences(): Collection
    {
        return $this->absences;
    }

    public function addAbsence(Absence $absence): self
    {
        if (!$this->absences->contains($absence)) {
            $this->absences->add($absence);
            $absence->setSession($this);
        }

        return $this;
    }

    public function removeAbsence(Absence $absence): self
    {
        if ($this->absences->removeElement($absence)) {
            // set the owning side to null (unless already changed)
            if ($absence->getSession() === $this) {
                $absence->setSession(null);
            }
        }

        return $this;
    }
}

src/Form/SessionType.php
<?php

namespace App\Form;

use App\Entity\Session;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class SessionType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('date')
            ->add('hourStart')
            ->add('hourEnd')
            ->add('label')
            ->add('day')
            ->add('lesson')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Session::class,
        ]);
    }
}

src/Controller/SessionController.php
<?php

namespace App\Controller;

use App\Entity\Absence;
use App\Entity\Session;
use App\Form\AbsenceType;
use App\Repository\AbsenceRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use WhiteOctober\BreadcrumbsBundle\Model\Breadcrumbs;



class SessionController extends AbstractController
{



    #[Route('/session/absence/edit/{id}', name: 'session_students_edit' , methods: ['POST', 'GET'])]
    public function editAbs(Absence $absence, AbsenceRepository $absenceRepository, Request $request, Breadcrumbs $breadcrumbs): Response
    {
        $label = $absence->getSession()->getLabel();
        if (strlen($label) > 20) {
            $label = substr($label, 0 ,20) . '...';
        }
        $breadcrumbs->addItem('Dashboard', $this->generateUrl('app_home'));
        $breadcrumbs->addItem('Cours', $this->generateUrl('app_lesson'));
        $breadcrumbs->addItem($label, $this->generateUrl('lesson_show_session', ['id' => $absence->getSession()->getLesson()->getId()]));
        $breadcrumbs->addItem('Séance du '. $absence->getSession()->getDate()->format('d/m/Y'), $this->generateUrl('lesson_show_session_student', ['id' => $absence->getSession()->getId()]));
        $breadcrumbs->addItem('Modification', $this->generateUrl('session_students_edit', ['id' => $absence->getId()]));
        if($this->getUser() === null){
            $this->addFlash('error', 'Vous devez vous connecter pour acceder a ce contenu');
            return $this->redirectToRoute('app_login');
        }

        if($this->getUser() === $absence->getSession()->getLesson()->getTeacher() || $this->getUser()->getRoles() === ['ROLE_ADMIN', 'ROLE_USER']){
            $form = $this->createForm(AbsenceType::class, $absence);
            $form->handleRequest($request);

            if ($form->isSubmitted() && $form->isValid()) {
                $absenceRepository->save($absence, true);

                return $this->redirectToRoute('lesson_show_session_student', ['id' => $absence->getSession()->getId()], Response::HTTP_SEE_OTHER);
            }

            return $this->renderForm('absence/edit.html.twig', [
                'absence' => $absence,
                'form' => $form,
            ]);
        }

        else{
            $this->addFlash('error', 'Vous n\'avez pas les droits pour acceder a ce contenu');
            return $this->redirectToRoute('lesson_show_session' , ['id' => $absence->getSession()->getLesson()->getId()]);
        }

    }
    /**
     * @param Session $session
     * @param EntityManagerInterface $manager
     * @param Request $request
     * @return JsonResponse|Response
     */
    #[Route('/session/delete/{id}', name: 'app_session_delete' , methods: ['DELETE'])]
    public function deleteJson(Session $session, EntityManagerInterface $manager, Request $request): JsonResponse|Response
    {
        if($this->getUser() === null){
            $this->addFlash('error', 'Vous devez vous connecter pour acceder a ce contenu');
            return $this->redirectToRoute('app_login');
        }
        $json = [];
        $date = $session->getDate()->format('d/m/Y');
        if ($session->getLesson()->getTeacher() === $this->getUser() or $this->getUser()->getRoles() === ['ROLE_ADMIN', 'ROLE_USER']) {
            if ($request->isXmlHttpRequest()) {
                $manager->remove($session);
                $manager->flush();

                $json = ['response' => 'ok',
                    'date' => $date,
                ];
                return new JsonResponse($json);
            }
        }

        return new Response ('error', 404);
    }
}

templates/session/session.html.twig
{% extends 'base.html.twig' %}

{% block style %}
    <link href="
{{ asset('assets/vendor/datatables/dataTables.bootstrap4.min.css') }}
" rel="stylesheet">
    <link href="
{{ asset('assets/css/lessonStyle.css') }}
" rel="stylesheet">
    <link href="https://cdn.datatables.net/buttons/2.3.6/css/buttons.dataTables.min.css" rel="stylesheet">

{% endblock %}
{% block title %}Class Checker - Scéances {% endblock %}

{% block body %}

<div id="alert">

</div>
<div style="width: 100%">

        <div class="me-5 ms-5 pt-2 mb-4">
            


            <h1 class="justify-content-center d-flex text-center text-dark">Liste des sessions du cours {{ lesson.label}} </h1>

            <table class="table table-hover table-bordered w-100" id="dataTable">
                <thead >
                <tr class="table-primary">
                    <th>DATE</th>
                    <th>HORAIRE</th>
                    <th>ACTION</th>
                </tr>
                </thead>


                    <tbody id="session">
                    {% for session in sessions %}
                    <tr class="" id="{{ session.id }}">
                        <td data-order="{{ session.date|date('U') }}" class="ps-2">{{ session.date | date('d/m/Y')}}
                        <td class="ps-2">{{ session.hourStart|date('H:i') }} à {{ session.hourEnd|date('H:i') }}</td>


                        <td class="ps-2" style="width:10em ">
                        <!-- Example single danger button -->
<div class="btn-group">
    <button type="button" class="btn btn-sm btn-outline-primary dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-share" viewBox="0 0 16 16">
        <path d="M13.5 1a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3zM11 2.5a2.5 2.5 0 1 1 .603 1.628l-6.718 3.12a2.499 2.499 0 0 1 0 1.504l6.718 3.12a2.5 2.5 0 1 1-.488.876l-6.718-3.12a2.5 2.5 0 1 1 0-3.256l6.718-3.12A2.5 2.5 0 0 1 11 2.5zm-8.5 4a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3zm11 5.5a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3z"/>
      </svg>
    </button>
    <ul class="dropdown-menu">
      <li class=" d-flex justify-content-center align-items-center"><a target="_blank" href="{{path('app_qr_codes', {id: session.id})}}" class="btn btn-outline-primary btn-sm"> <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-qr-code" viewBox="0 0 16 16">
      <path d="M2 2h2v2H2V2Z"/>
      <path d="M6 0v6H0V0h6ZM5 1H1v4h4V1ZM4 12H2v2h2v-2Z"/>
      <path d="M6 10v6H0v-6h6Zm-5 1v4h4v-4H1Zm11-9h2v2h-2V2Z"/>
      <path d="M10 0v6h6V0h-6Zm5 1v4h-4V1h4ZM8 1V0h1v2H8v2H7V1h1Zm0 5V4h1v2H8ZM6 8V7h1V6h1v2h1V7h5v1h-4v1H7V8H6Zm0 0v1H2V8H1v1H0V7h3v1h3Zm10 1h-1V7h1v2Zm-1 0h-1v2h2v-1h-1V9Zm-4 0h2v1h-1v1h-1V9Zm2 3v-1h-1v1h-1v1H9v1h3v-2h1Zm0 0h3v1h-2v1h-1v-2Zm-4-1v1h1v-2H7v1h2Z"/>
      <path d="M7 12h1v3h4v1H7v-4Zm9 2v2h-3v-1h2v-1h1Z"/>
    </svg></a></li>

      <li class=" d-flex justify-content-center align-items-center mt-1"> <a  class="btn btn-outline-primary btn-sm"> <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-link-45deg" viewBox="0 0 16 16">
      <path d="M4.715 6.542 3.343 7.914a3 3 0 1 0 4.243 4.243l1.828-1.829A3 3 0 0 0 8.586 5.5L8 6.086a1.002 1.002 0 0 0-.154.199 2 2 0 0 1 .861 3.337L6.88 11.45a2 2 0 1 1-2.83-2.83l.793-.792a4.018 4.018 0 0 1-.128-1.287z"/>
      <path d="M6.586 4.672A3 3 0 0 0 7.414 9.5l.775-.776a2 2 0 0 1-.896-3.346L9.12 3.55a2 2 0 1 1 2.83 2.83l-.793.792c.112.42.155.855.128 1.287l1.372-1.372a3 3 0 1 0-4.243-4.243L6.586 4.672z"/>
    </svg></a></li>
    </ul>
  </div>
                        
                            

                          {# <input id="input" value="{{path('app_url',  {id: session.id})}}"/>
<button id="copy">Copier</button> #}
                         

                            <a class="btn btn-outline-primary btn-sm" href="{{ path('lesson_show_session_student', {id: session.id}) }}">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="logo-blue bi bi-eye-fill" viewBox="0 0 16 16">
                                    <path d="M10.5 8a2.5 2.5 0 1 1-5 0 2.5 2.5 0 0 1 5 0z"/>
                                    <path d="M0 8s3-5.5 8-5.5S16 8 16 8s-3 5.5-8 5.5S0 8 0 8zm8 3.5a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7z"/>
                                </svg>
                            </a>
                            
                            <a class="btn btn-outline-danger btn-sm mt-1" onclick="delSesson({{ session.id }})"> <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-trash3" viewBox="0 0 16 16">
                            <path d="M6.5 1h3a.5.5 0 0 1 .5.5v1H6v-1a.5.5 0 0 1 .5-.5ZM11 2.5v-1A1.5 1.5 0 0 0 9.5 0h-3A1.5 1.5 0 0 0 5 1.5v1H2.506a.58.58 0 0 0-.01 0H1.5a.5.5 0 0 0 0 1h.538l.853 10.66A2 2 0 0 0 4.885 16h6.23a2 2 0 0 0 1.994-1.84l.853-10.66h.538a.5.5 0 0 0 0-1h-.995a.59.59 0 0 0-.01 0H11Zm1.958 1-.846 10.58a1 1 0 0 1-.997.92h-6.23a1 1 0 0 1-.997-.92L3.042 3.5h9.916Zm-7.487 1a.5.5 0 0 1 .528.47l.5 8.5a.5.5 0 0 1-.998.06L5 5.03a.5.5 0 0 1 .47-.53Zm5.058 0a.5.5 0 0 1 .47.53l-.5 8.5a.5.5 0 1 1-.998-.06l.5-8.5a.5.5 0 0 1 .528-.47ZM8 4.5a.5.5 0 0 1 .5.5v8.5a.5.5 0 0 1-1 0V5a.5.5 0 0 1 .5-.5Z"/>
                          </svg></a>
                            
                            
                        </td>

                    </tr>
                    {% endfor %}
                    </tbody>

            </table>
        </div>
    </div>
{% endblock %}

{% block script %}
    <script src="{{ asset('assets/js/ajaxDeleteSesson.js') }}"></script>
    <script src="{{ asset('assets/js/copyScript.js') }}"></script>
{% endblock %}

templates/session/students.html.twig
{% extends 'base.html.twig' %}

{% block style %}
    <link href="
{{ asset('assets/vendor/datatables/dataTables.bootstrap4.min.css') }}
" rel="stylesheet">
    <link href="
{{ asset('assets/css/lessonStyle.css') }}
" rel="stylesheet">
    <link href="https://cdn.datatables.net/buttons/2.3.6/css/buttons.dataTables.min.css" rel="stylesheet">

{% endblock %}
{% block title %}Class Checker - Séance du {{ session.date | date('d/m/Y') }}{% endblock %}

{% block body %}

<div id="alert">

</div>
<div style="width: 100%">

        <div class="me-5 ms-5 pt-2 mb-4">
            


            <h3 class="justify-content-center d-flex text-center text-dark">Séance du {{ session.date | date('d/m/Y') }}</h3>

            <table class="table table-hover table-bordered w-100" id="dataTable">
                <thead >
                <tr class="table-primary">
                    <th>NOM PRENOM</th>
                    <th>STATUS</th>
                    <th>DATE</th>
                    <th>ACTION</th>
                </tr>
                </thead>


                    <tbody id="session">
                    {% if absences is not null %}
                    {% for absence in absences %}
                    <tr class="" id="{{ absence.id }}">
                        <td class="ps-2">{{ absence.students.name }} {{ absence.students.surname }}</td>
                        <td class="ps-2">
                            {% if absence.justify.status is same as 0 %}
                            Absent
                            {% elseif absence.justify.status is same as 1 %}
                            Justifié
                            {% elseif absence.justify.status is same as 2 %}
                            Présent
                            {% endif %}
                        </td>
                        <td class="ps-2">{{ absence.dateJustify|date('d/m/Y') }}</td>

                        <td class="ps-2" style="width:10em ">
                            <a class="btn btn-outline-primary btn-sm" href="{{ path('session_students_edit', {id: absence.id}) }}">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="logo-blue bi bi-eye-fill" viewBox="0 0 16 16">
                                    <path d="M10.5 8a2.5 2.5 0 1 1-5 0 2.5 2.5 0 0 1 5 0z"/>
                                    <path d="M0 8s3-5.5 8-5.5S16 8 16 8s-3 5.5-8 5.5S0 8 0 8zm8 3.5a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7z"/>
                                </svg>
                            </a>
                        </td>

                    </tr>
                    {% endfor %}
                    {% else %}
                    <tr>
                        Il ni a personne.
                    </tr>
                    {% endif %}
                    </tbody>

            </table>
        </div>
    </div>
{% endblock %}

{% block script %}
    <script src="{{ asset('assets/js/ajaxDeleteSesson.js') }}"></script>
{% endblock %}