src/Entity/ToHave.php
<?php

namespace App\Entity;

use App\Repository\ToHaveRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

#[ORM\Entity(repositoryClass: ToHaveRepository::class)]
#[UniqueEntity(fields: ['students'], message: 'Un ou plusieurs élèves sont déjà attribué a ce cour')]
class ToHave
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'toHave')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Student $students = null;

    #[ORM\ManyToOne(inversedBy: 'toHave')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Lesson $Lessons = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getStudents(): ?Student
    {
        return $this->students;
    }

    public function setStudents(?Student $students): self
    {
        $this->students = $students;

        return $this;
    }

    public function getLessons(): ?Lesson
    {
        return $this->Lessons;
    }

    public function setLessons(?Lesson $Lessons): self
    {
        $this->Lessons = $Lessons;

        return $this;
    }

}

src/Form/UserType.php
<?php

namespace App\Form;

use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\RepeatedType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextType;

/**
 * @author LUCAS V
 */
class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('email',TextType::class,[
                'attr' => [
                    'class' => 'form-control'
                ],
                'label' => 'Email',
                'label_attr' => [
                    'class' => 'form-label mt-5'
                ],
            ])
            ->add('date_naissance', DateType::class, [
                'attr' => [
                    'class' => 'form-control'
                ],
                'label' => 'Date de naissance',
                'html5' => true,
                'widget' => 'single_text',
                'label_attr' => [
                    'class' => 'form-label mt-5'

                ]
            ])
            ->add('nom',TextType::class, [
                'attr' => [
                    'class' => 'form-control'
                ],
                'label' => 'Nom',
                'label_attr' => [
                    'class' => 'form-label mt-1'
                ],
            ])
            ->add('prenom',TextType::class, [
                'attr' => [
                    'class' => 'form-control'
                ],
                'label' => 'Prénom',
                'label_attr' => [
                    'class' => 'form-label mt-1'
                ],
            ])
            ->add('telephone',TextType::class, [
                'attr' => [
                    'class' => 'form-control'
                ],
                'label' => 'Téléphone',
                'label_attr' => [
                    'class' => 'form-label mt-5'
                ],
            ])
            ->add('sexe',ChoiceType::class, [
                'attr' => [
                    'class' => 'form-control'
                ],
                'label' => 'Sexe',
                'label_attr' => [
                    'class' => 'form-label mt-5'
                ],
                'choices' => ['Homme' => 'Homme', 'Femme' => 'Femme']
            ])
            ->add('plainPassword', RepeatedType::class, [
                'type' => PasswordType::class,
                'first_options'  =>
                    ['attr' => [
                    'class' => 'form-control '
                ],
                        'label' => 'Mot de passe',
                        'hash_property_path' => 'password',
                        'label_attr' => [
                            'class' => 'form-label mt-5'
                        ],
                    ],
                'second_options' =>
                    [
                        'attr' => [
                            'class' => 'form-control '
                        ],
                        'label' => 'Repeter mot de passe',
                        'label_attr' => [
                            'class' => 'form-label mt-5'
                        ],

                    ],
                'mapped' => false,
            ])
            ->add('submit', SubmitType::class, [
                'attr' => [
                    'class' => 'btn btn-outline-success mt-4'
                ],
                'label' => 'Valider'
            ]);

                
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => User::class,
        ]);
    }
}

src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Form\UserEditType;
use App\Form\UserType;
use App\Repository\UserRepository;
use DateTime;
use DateTimeInterface;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;
use Scheb\TwoFactorBundle\Model\Email\TwoFactorInterface;
use Symfony\Component\HttpFoundation\JsonResponse;
use WhiteOctober\BreadcrumbsBundle\Model\Breadcrumbs;


#[Route('/user')]
class UserController extends AbstractController
{
    #[Route('/', name: 'app_user_index', methods: ['GET'])]
    public function index(UserRepository $userRepository,Breadcrumbs $breadcrumbs): Response
    {
        $breadcrumbs->addItem('Dashboard', $this->generateUrl('app_home'));
        $breadcrumbs->addItem('Utilisateur', $this->generateUrl('app_user_index')); 
        if($this->getUser() === null){
            $this->addFlash('error', 'Vous devez vous connecter pour acceder a ce contenu');
            return $this->redirectToRoute('app_login');
        }
        if($this->getUser()->getRoles() != ['ROLE_ADMIN', 'ROLE_USER']){
            return $this->redirectToRoute('app_home');
        }
        $currentUser = $this->getUser();
        return $this->render('user/index.html.twig', [
            'users' => $userRepository->findAll(),
            'currentUser' => $currentUser,
    
        ]);
    }

    #[Route('/new', name: 'app_user_new', methods: ['GET', 'POST'])]
    public function new(Request $request, UserRepository $userRepository,EntityManagerInterface $manager, UserPasswordHasherInterface $passwordHasher, Breadcrumbs $breadcrumbs): Response
    {
        $breadcrumbs->addItem('Dashboard', $this->generateUrl('app_home'));
        $breadcrumbs->addItem('Utilisateur', $this->generateUrl('app_user_index'));
        $breadcrumbs->addItem('Créer', $this->generateUrl('app_user_new'));

        if($this->getUser() === null){
            $this->addFlash('error', 'Vous devez vous connecter pour acceder a ce contenu');
            return $this->redirectToRoute('app_login');
        }
        if($this->getUser()->getRoles() != ['ROLE_ADMIN', 'ROLE_USER']){
            return $this->redirectToRoute('app_home');
        }
        $currentUser = $this->getUser();
        $user = new User();
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $user = $form->getData();
            $admin = $request->get('roles');
            if ($admin === 'oui'){
                $roles = ["ROLE_ADMIN"];
                $user->setRoles($roles);
            }else {
                $user->setRoles([]);
            }
            $manager->persist($user);
            $manager->flush();
            return $this->redirectToRoute('app_user_index', [], Response::HTTP_SEE_OTHER);
        }
        return $this->renderForm('user/new.html.twig', [
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_user_show', methods: ['GET'])]
    public function show(User $user): Response
    {
        if($this->getUser() === null){
            $this->addFlash('error', 'Vous devez vous connecter pour acceder a ce contenu');
            return $this->redirectToRoute('app_login');
        }
        if($this->getUser()->getRoles() != ['ROLE_ADMIN', 'ROLE_USER']){
            return $this->redirectToRoute('app_home');
        }
        return $this->render('user/show.html.twig', [
            'user' => $user,
        ]);
    }

    #[Route('/edit/{id}', name: 'app_user_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, User $user, UserRepository $userRepository, Breadcrumbs $breadcrumbs): Response
    {
        $breadcrumbs->addItem('Dashboard', $this->generateUrl('app_home'));
        $breadcrumbs->addItem('Utilisateur', $this->generateUrl('app_user_index'));
        $breadcrumbs->addItem('Modifier', $this->generateUrl('app_user_edit', ['id' => $user->getId()]));
        
        if($this->getUser() === null){
            $this->addFlash('error', 'Vous devez vous connecter pour acceder a ce contenu');
            return $this->redirectToRoute('app_login');
        }
        if($this->getUser()->getRoles() != ['ROLE_ADMIN', 'ROLE_USER']){
            return $this->redirectToRoute('app_home');
        }
        $currentUser = $this->getUser();
        $form = $this->createForm(UserEditType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $admin = $request->get('roles');
            if ($admin === 'oui'){
                $roles = ["ROLE_ADMIN"];
                $user->setRoles($roles);
            }else {
                $user->setRoles([]);
            }
            $userRepository->save($user, true);

            return $this->redirectToRoute('app_user_index', [], Response::HTTP_SEE_OTHER);
        }
        return $this->renderForm('user/edit.html.twig', [
            'user' => $user,
            'form' => $form,
        ]);
    }

    #[Route('/editProfile/{id}', name: 'app_user_editProfil', methods: ['POST'])]
    public function editProfil(Request $request, User $user, UserRepository $userRepository): JsonResponse|Response
    {

        if($this->getUser() === null){
            $this->addFlash('error', 'Vous devez vous connecter pour acceder a ce contenu');
            return $this->redirectToRoute('app_login');
        }
        $json = [];
        if($request->isXmlHttpRequest() || $request->query->get('showJson') === 1){
            $user->setNom($request->get('nom'))
                ->setPrenom($request->get('prenom'))
                ->setEmail($request->get('email'))
                ->setDateNaissance(date_create($request->get('dateNaissance')))
                ->setTelephone($request->get('tel'))
                ->setSexe($request->get('sexe'));
            if($userRepository->save($user, true)){
                $json = ['response' => 'ok'];
            }else{
                $json = ['response' => 'ko'];
            }            
        }else {
            $json = ['response' => 'ko'];
        }
        return new JsonResponse($json);
    }

    #[Route('/delete/{id}', name: 'app_user_delete', methods: ['GET'])]
    public function delete(Request $request, User $user, UserRepository $userRepository, EntityManagerInterface $manager): Response
    {
        if($this->getUser() === null){
            $this->addFlash('error', 'Vous devez vous connecter pour acceder a ce contenu');
            return $this->redirectToRoute('app_login');
        }
            $currentUser = $this->getUser();

            if (!$user) {
                $this->addFlash(
                    'warning',
                    "Le cour n'a pas été trouvé!"
                );
                return $this->redirectToRoute('app_user_index');
            }
    
            $manager->remove($user);
            $manager->flush();
            $this->addFlash(
                'success',
                'Le professeur à été supprimé avec succès !'
            );
            return $this->redirectToRoute('app_user_index', ['currentUser' => $currentUser,]);

        
    }
    #[Route('/profil/{id}', name: 'app_profil', methods:['GET'])]
    public function profil(): Response
    {
        if($this->getUser() === null){
            $this->addFlash('error', 'Vous devez vous connecter pour acceder a ce contenu');
            return $this->redirectToRoute('app_login');
        }
        $currentUser = $this->getUser();
        return $this->render('user/Profile.html.twig', ['currentUser' => $currentUser,]);
    }
    }

templates/user/Profile.html.twig
{% extends 'base.html.twig' %}
    {% block title %}Class Checker - Profile
        
    {% endblock %}
    

    {% block body %}
        <link href="{{asset('assets/css/ProfileStyle.css')}}" rel="stylesheet">
{# ========== #}


<div class="d-flex justify-content-center container">
  
    <form id="editProfil" class="well form-horizontal" action="{{ path('app_user_editProfil', {id: app.user.id})}}" method="post"  id="contact_form">
<fieldset>

<!-- Form Name -->
<legend class="txt-black d-flex  justify-content-center">Bienvenue sur votre Profile {{ app.user.prenom }} {{ app.user.nom }}</legend>

<!-- Text input-->

<div class="form-group">
  <label class="col-md-4 control-label">Nom</label>  
  <div class="col-md-4 inputGroupContainer">
  <div class="input-group">
  <span class="input-group-text"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-fill" viewBox="0 0 16 16">
  <path d="M3 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H3Zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6Z"/>
</svg></span>
  <input id="nom" name="nom" placeholder="Nom" value="{{ app.user.nom }}" class="form-control"  type="text">
    </div>
  </div>
</div>

<!-- Text input-->

<div class="form-group">
  <label class="col-md-4 control-label" >Prénom</label> 
    <div class="col-md-4 inputGroupContainer">
    <div class="input-group">
  <span class="input-group-text"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-fill" viewBox="0 0 16 16">
  <path d="M3 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H3Zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6Z"/>
</svg></span>
  <input id="prenom" name="prenom" placeholder="Prénom" value="{{ app.user.prenom }}" class="form-control"  type="text">
    </div>
  </div>
</div>

<!-- Text input-->
       <div class="form-group">
  <label class="col-md-4 control-label">E-Mail</label>  
    <div class="col-md-4 inputGroupContainer">
    <div class="input-group">
        <span class="input-group-text"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-envelope-fill" viewBox="0 0 16 16">
        <path d="M.05 3.555A2 2 0 0 1 2 2h12a2 2 0 0 1 1.95 1.555L8 8.414.05 3.555ZM0 4.697v7.104l5.803-3.558L0 4.697ZM6.761 8.83l-6.57 4.027A2 2 0 0 0 2 14h12a2 2 0 0 0 1.808-1.144l-6.57-4.027L8 9.586l-1.239-.757Zm3.436-.586L16 11.801V4.697l-5.803 3.546Z"/>
      </svg></span>
  <input id="email" name="email" placeholder="E-Mail" value="{{ app.user.email }}" class="form-control"  type="text">
    </div>
  </div>
</div>


<!-- Text input-->
       
<div class="form-group">
  <label class="col-md-4 control-label">Téléphone</label>  
    <div class="col-md-4 inputGroupContainer">
    <div class="input-group">
        <span class="input-group-text"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-telephone-fill" viewBox="0 0 16 16">
        <path fill-rule="evenodd" d="M1.885.511a1.745 1.745 0 0 1 2.61.163L6.29 2.98c.329.423.445.974.315 1.494l-.547 2.19a.678.678 0 0 0 .178.643l2.457 2.457a.678.678 0 0 0 .644.178l2.189-.547a1.745 1.745 0 0 1 1.494.315l2.306 1.794c.829.645.905 1.87.163 2.611l-1.034 1.034c-.74.74-1.846 1.065-2.877.702a18.634 18.634 0 0 1-7.01-4.42 18.634 18.634 0 0 1-4.42-7.009c-.362-1.03-.037-2.137.703-2.877L1.885.511z"/>
      </svg></span>
  <input name="tel" id="tel" placeholder="+33 6 32 25 45 98" value="{{ app.user.telephone }}" class="form-control" type="text">
    </div>
  </div>
</div>

<!-- Text input-->
      
<div class="form-group">
  <label class="col-md-4 control-label">Date Naissance</label>  
    <div class="col-md-4 inputGroupContainer">
    <div class="input-group">
        <span class="input-group-text"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-calendar2-date-fill" viewBox="0 0 16 16">
        <path d="M9.402 10.246c.625 0 1.184-.484 1.184-1.18 0-.832-.527-1.23-1.16-1.23-.586 0-1.168.387-1.168 1.21 0 .817.543 1.2 1.144 1.2z"/>
        <path d="M3.5 0a.5.5 0 0 1 .5.5V1h8V.5a.5.5 0 0 1 1 0V1h1a2 2 0 0 1 2 2v11a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V3a2 2 0 0 1 2-2h1V.5a.5.5 0 0 1 .5-.5zm9.954 3H2.545c-.3 0-.545.224-.545.5v1c0 .276.244.5.545.5h10.91c.3 0 .545-.224.545-.5v-1c0-.276-.244-.5-.546-.5zm-4.118 9.79c1.258 0 2-1.067 2-2.872 0-1.934-.781-2.668-1.953-2.668-.926 0-1.797.672-1.797 1.809 0 1.16.824 1.77 1.676 1.77.746 0 1.23-.376 1.383-.79h.027c-.004 1.316-.461 2.164-1.305 2.164-.664 0-1.008-.45-1.05-.82h-.684c.047.64.594 1.406 1.703 1.406zm-2.89-5.435h-.633A12.6 12.6 0 0 0 4.5 8.16v.695c.375-.257.969-.62 1.258-.777h.012v4.61h.675V7.354z"/>
      </svg></span>
  <input name="dateNaissance" id="date" value="{{ app.user.dateNaissance | date('Y-m-d') }}" class="form-control" type="date">
    </div>
  </div>
</div>

<!-- Select Basic -->
   
<div class="form-group"> 
  <label class="col-md-4 control-label">Genre</label>
    <div class="col-md-4 selectContainer">
    <div class="input-group">
        <span class="input-group-text"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-gender-ambiguous" viewBox="0 0 16 16">
        <path fill-rule="evenodd" d="M11.5 1a.5.5 0 0 1 0-1h4a.5.5 0 0 1 .5.5v4a.5.5 0 0 1-1 0V1.707l-3.45 3.45A4 4 0 0 1 8.5 10.97V13H10a.5.5 0 0 1 0 1H8.5v1.5a.5.5 0 0 1-1 0V14H6a.5.5 0 0 1 0-1h1.5v-2.03a4 4 0 1 1 3.471-6.648L14.293 1H11.5zm-.997 4.346a3 3 0 1 0-5.006 3.309 3 3 0 0 0 5.006-3.31z"/>
      </svg></span>
    <select id="genre" name="sexe" class="form-control selectpicker" >
      <option  >{{ app.user.sexe }}</option>
      {% if app.user.sexe =="Homme" %}
        <option>Femme</option>
        {% else %}
            <option>Homme</option>        
      {% endif %}
    </select>
  </div>
</div>
</div>



<!-- Success message -->
<div class="alert alert-success" role="alert" id="success_message">Success <i class="glyphicon glyphicon-thumbs-up"></i> Thanks for contacting us, we will get back to you shortly.</div>

<!-- Button -->
<div class="form-group">
  <label class="col-md-4 control-label"></label>
  <div class="col-md-4 d-flex justify-content-between">
    <button id="submit" type="submit" class="btn btn-outline-success" >Modifier <span class="glyphicon glyphicon-send"></span></button>
    <a href="{{path('app_mdp')}}" class="btn btn-outline-warning" >Mot de Passe<span class="glyphicon glyphicon-send"></span></a>
  </div>
</div>


</fieldset>
</form>
</div>
    </div><!-- /.container -->





        




    {% endblock %}
    {% block script %}
        <script src="{{ asset('assets/js/ajaxProfilScript.js') }}"></script>
        <script src="{{ asset('assets/js/profilScript.js') }}"></script>
    {% endblock %}
       

templates/user/_delete_form.html.twig
<form method="post" action="{{ path('app_user_delete', {'id': user.id}) }}" onsubmit="return confirm('Etes vous sur de vouloir supprimer?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ user.id) }}">
    <button class="btn">Delete</button>
</form>

templates/user/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-outline-info btn-sm mt-2" >{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/user/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Class Checker - Modification d'un utilisateur{% endblock %}

{% block body %}
    <div class="container mt-5">
            <h1 class="text-center text-dark">Modification d'un utilisateur</h1>

        {{ form_start(form) }}
        <div class="row">
            <div class="d-flex mt-5">
                <label class="form-label" for="roles">Administrateur: </label>
                <div>
                    <label for="oui" class="form-check-label mx-4">Oui</label>
                    <input id="oui" class="form-check-input" name="roles" type="radio" value="oui" {% if user.roles is same as (["ROLE_ADMIN", "ROLE_USER"]) %} checked {% endif %}>
                    <label for="non" class="form-check-label mx-4">Non</label>
                    <input id="non" class="form-check-input" name="roles" type="radio" value="non" {% if user.roles is same as (["ROLE_USER"] )%} checked {% endif %}>
                </div>

            </div>
            <div class="col">
                {{ form_label(form.nom) }}
                {{ form_widget(form.nom) }}
                {{ form_errors(form.nom) }}
            </div>
            <div class="col">
                {{ form_label(form.prenom) }}
                {{ form_widget(form.prenom) }}
                {{ form_errors(form.prenom) }}
            </div>
        </div>

        <div class="row">
            <div class="col">
                {{ form_label(form.email) }}
                {{ form_widget(form.email) }}
                {{ form_errors(form.email) }}
            </div>
            <div class="col">
                {{ form_label(form.date_naissance) }}
                {{ form_widget(form.date_naissance) }}
                {{ form_errors(form.date_naissance) }}
            </div>
        </div>

        <div class="row">
            <div class="col">
                {{ form_label(form.telephone) }}
                {{ form_widget(form.telephone) }}
                {{ form_errors(form.telephone) }}
            </div>
            <div class="col">
                {{ form_label(form.sexe) }}
                {{ form_widget(form.sexe) }}
                {{ form_errors(form.sexe) }}
            </div>
        </div>

        <div class="mt-3 d-flex justify-content-evenly">
            <a class="mt-4 ms-5 btn btn-outline-danger" href="{{ path('app_user_index') }}">Annuler</a>
            {{ form_row(form.submit) }}
        </div>
        {{ form_end(form) }}
    </div>

{% endblock %}

templates/user/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Class Checker - Liste des profs{% endblock %}
{% block style %}
    <link href="
{{ asset('assets/vendor/datatables/dataTables.bootstrap4.min.css') }}
" rel="stylesheet">
    <link href="https://cdn.datatables.net/buttons/2.3.6/css/buttons.dataTables.min.css" rel="stylesheet">
{% endblock %}
{% block body %}

    {% for message in app.flashes('success')%}
        <div class="flash" data-state=success><strong>{{ message }}</strong></div>
    {% endfor %}

    <div class="mx-lg-5 " style="width: 95%">
        <h3 class="justify-content-center d-flex text-center text-dark">Liste des professeurs</h3>

            <table class="table table-hover table-bordered" id="dataTable">
                <thead >
                <tr class="table-primary">
                    <th>EMAIL</th>
                    <th>COURS</th>
                    <th>DATE NAISS</th>
                    <th>NOM</th>
                    <th>PRENOM</th>
                    <th>TELEPHONE</th>
                    <th>SEXE</th>
                    <th>ACTION</th>
                </tr>
                </thead>
                <tbody>
                {% for  user in users %}
                    <tr>
                        <td class="ps-2">{{ user.email }}</td>
                        <td class="ps-2">{{ user.lessons.count}}</td>
                        <td class="ps-2">{{ user.dateNaissance|date('d/m/Y') }}</td>
                        <td class="ps-2">{{ user.nom|upper }}</td>
                        <td class="ps-2">{{ user.prenom }}</td>
                        <td class="ps-2">{{ user.telephone }}</td>
                        <td class="ps-2">{{ user.sexe }}</td>
                        <td class="ps-2" style="width:6em ">
                            <a class="btn btn-outline-warning btn-sm" href="{{ path('app_user_edit', {id: user.id}) }}" ><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
                            <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
                            <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"/>
                          </svg></a>

                            <a class="btn btn-outline-danger btn-sm" onclick="return confirm('Voulez vous vraiment supprimer l\'éléve')" href="{{ path('app_user_delete', {id: user.id}) }}" ><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash3" viewBox="0 0 16 16">
                            <path d="M6.5 1h3a.5.5 0 0 1 .5.5v1H6v-1a.5.5 0 0 1 .5-.5ZM11 2.5v-1A1.5 1.5 0 0 0 9.5 0h-3A1.5 1.5 0 0 0 5 1.5v1H2.506a.58.58 0 0 0-.01 0H1.5a.5.5 0 0 0 0 1h.538l.853 10.66A2 2 0 0 0 4.885 16h6.23a2 2 0 0 0 1.994-1.84l.853-10.66h.538a.5.5 0 0 0 0-1h-.995a.59.59 0 0 0-.01 0H11Zm1.958 1-.846 10.58a1 1 0 0 1-.997.92h-6.23a1 1 0 0 1-.997-.92L3.042 3.5h9.916Zm-7.487 1a.5.5 0 0 1 .528.47l.5 8.5a.5.5 0 0 1-.998.06L5 5.03a.5.5 0 0 1 .47-.53Zm5.058 0a.5.5 0 0 1 .47.53l-.5 8.5a.5.5 0 1 1-.998-.06l.5-8.5a.5.5 0 0 1 .528-.47ZM8 4.5a.5.5 0 0 1 .5.5v8.5a.5.5 0 0 1-1 0V5a.5.5 0 0 1 .5-.5Z"/>
                          </svg></a>
                          
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
{% endblock %}